### ISSUE TITLE
Perhaps don't change current dir when --path is specified?

### ISSUE THREAD

**Issue by brunocassol** [acoshift/goreload#2]
This is a common structure for Go projects:

```
/cmd
  /app1
    main.go
  /app2
    main.go
shared1.go
shared2.go
```

So to have /cmd/app1/main.go autoreload even when shared1.go or shared2.go file is edited I do:
```
$ cd cmd/app1
$ goreload --path ../../
```

This however doesn't work because goreload [changes current dir](https://github.com/acoshift/goreload/blob/d994e0b16caa37ea2a1a825acba483a1dafd67c9/internal/builder.go#L60) to the specified `--path` before issuing the build command and tells go to build on the root of the project `/cmd/app1/../..` instead of doing what I expected: build on current directory but watch for file changes in parent directories also.

After digging code I found there there is an error not being checked which made goreload think the build went fine.

My suggestion, which solved those issues, is to remove `command.Dir = b.dir` from [builder.go:60](https://github.com/acoshift/goreload/blob/d994e0b16caa37ea2a1a825acba483a1dafd67c9/internal/builder.go#L60) and add some error checking to the if blocks at [builder.go:64](https://github.com/acoshift/goreload/blob/d994e0b16caa37ea2a1a825acba483a1dafd67c9/internal/builder.go#L64) so it reads like this:

```
	if err != nil {
		b.errors = err.Error()
	} else if command.ProcessState.Success() {
		b.errors = ""
	} else {
		b.errors = string(output)
	}
```

Please let me know what you think and feel free to apply those changes if they look good to you.

**Comment by acoshift** [comment]
Thank you very much!!. I change the code and it works well!! xD
